refactor: Enhance configure script with improved error handling and package checks

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,48 +1,136 @@
-#!/bin/env bash
+#!/usr/bin/env bash
 
-set -e
-
-# Check if a package is installed
-function check_installed () { dpkg -s "$1" &>/dev/null ; }
+set -eo pipefail
 
 function reset_env () {
+
     rm -rv debian/.* debian/"$(basename "$(pwd)")" \
-        debian/files \ debian/{changelog,changelog.gz} 2>/dev/null \
-        man/*.gz doc/man/"$(basename "$(pwd)")".{1,conf.5} || true
+        debian/files \
+        debian/{changelog,changelog.gz} 2>/dev/null \
+        debian/*.substvars \
+        debian/*.ex \
+        debian/*.debhelper \
+        man/"$(basename "$(pwd)")".{1,5,8} || true
+
+        # shellcheck disable=SC2181
+        if [ "$?" -eq 0 ] ; then
+            echo -e "\033[32mEnvironment reset successfully.\033[0m"
+        else
+            echo -e "\033[31mFailed to reset the environment.\033[0m"
+            exit 1
+        fi
 }
 
 function build_deb () {
 
-    local _signing
+    local _arch _no_sign _key _root_command
 
-    echo "Building the DEB package..."
+    _sign_key=
+    _no_sign=""
+    _target_arch=( "$(dpkg --print-architecture)" )
+    _root_command=fakeroot
+    _arches=()
 
-    shift || true
+    # Manually required system packages
+    _required=( debhelper dh-make git dh-gitchangelog pandoc coreutils )
+    _missing=()
 
-    while true ; do case "$1" in
-        --gpg-id                ) _gpg_id="$2"              ; shift  ;;
-        --no-sign               ) _sign=false                        ;;
-        --*                     ) echo "Unknown option: $1" ; exit 1 ;;
-        *                       )
-            if test -n "$2" ; then shift ; else break ; fi
-        ;;
-    esac ; done
+    shift
 
-    # shellcheck disable=SC2015
-    if [ -n "$_gpg_id" ] && [ "$_sign" = "false" ] ; then
-        echo "GPG signing ID is required for signing the package!" ; exit 1
-    elif [ -n "$_gpg_id" ] && [ "$_sign" = "true" ] ; then
-        echo "Signing the package with GPG ID: $_gpg_id"
-        _signing="--sign-keyid=$_gpg_id"
-    elif [ -z "$_gpg_id" ] && [ "$_sign" = "false" ] ; then
-        _signing="--no-sign"
+    while [ $# -gt 0 ] ; do case "$1" in
+            --build-type            )
+                case "$2" in
+                    binary|source|full )
+                        _type="$2" ; shift ;;
+                    *                  )
+                        echo "Invalid build type: $2" ; exit 1
+                ;;
+                esac
+            ;;
+            --sign-key              ) _key="$2" ; shift ;;
+            --no-sign               ) _no_sign="--no-sign" ;;
+            --root-command          )
+                case "$2" in
+                    fakeroot|sudo|super|really )
+                        _root="--root-command=$_root_command" ;;
+                    *                          )
+                        echo "Invalid root command: $2" ; exit 1
+                    ;;
+                esac
+            ;;
+            --*                     ) echo "Unknown option: $1" ; exit 1 ;;
+        esac ; shift ; done
+
+    # If no --target-arch was provided, use the default architecture
+    if [ -n "$_no_sign" ] && [ -n "$_key" ] ; then
+        echo "$_waring The --sign-key option is ignored because --no-sign is set."
+        _sign_key=""
     fi
 
-    if [ "$_sign" = "false" ] ; then _no_sign="--no-sign" ; else _no_sign="" ; fi
+    if [ -n "$_key" ] ; then
+        if ! gpg --list-keys "$_key" &>/dev/null ; then
+            echo "$_fail GPG key $_key not found."
+            exit 1
+        fi
+        _sign_key="--sign-key=$_key"
+    fi
 
-    echo ""
-    sleep 0.5
-    dpkg-buildpackage -b "$_signing" --root-command=fakeroot
+    if [ ! -d "debian" ] ; then
+        echo "The debian directory is missing. Please run \`dh_make\` first."
+        exit 1
+    fi
+
+    # Check if the HowToNebie APT repository is available
+    if ! grep -qr "howtonebie" /etc/apt/ 2>/dev/null; then
+        echo -e "$_missingRepo"
+    else
+        echo -e "configure: Detected HowToNebie APT repository."
+    fi
+
+    for pkg in "${_required[@]}"; do
+        if dpkg -s "$pkg" &>/dev/null "$pkg"; then
+            echo -e "configure: Checking for $pkg $_pass"
+        else
+            echo -e "configure: Checking for $pkg $_fail"
+            _missing+=( "$pkg" )
+        fi
+    done
+
+    # If _missing is not empty, print a message and exit
+    if [ ${#_missing[@]} -ne 0 ]; then
+        echo -e "configure: The following packages are missing:\n"
+        for pkg in "${_missing[@]}"; do echo -e "  - $pkg" ; done
+        echo -e "\nPlease install them using your package manager (e.g. \`sudo apt install <package>\`)"
+        exit 1
+    fi
+
+    for m in man/*.md; do
+        base=$(basename "$m" .md)
+        out="man/${base}"
+        pandoc "$m" -s -t man -o "$out"
+    done
+
+    dh_gitchangelog
+
+    if [ "$_type" = "source" ] || [ "$_type" = "full" ] ; then
+        # Compress the source package into a tarball
+        _version=$(cat doc/version)
+        cd ../ ; tar -czf "${_app_name}_$_version.orig.tar.gz" "$_app_name"
+        cd "$_app_name"
+    fi
+
+
+    for arch in "${_target_arch[@]}"; do
+        # shellcheck disable=SC2086
+        dpkg-buildpackage ${_root} ${_no_sign} ${_sign_key} --target-arch "$arch" --build=${_type:-binary}
+        # shellcheck disable=SC2181
+        if [ $? -ne 0 ]; then
+            echo -e "$_fail Failed to build package for architecture: $arch"
+            exit 1
+        else
+            echo -e "$_pass Successfully built package for architecture: $arch"
+        fi
+    done
 
 }
 
@@ -50,8 +138,7 @@ function manual_install () {
 
     echo "Installing the application..."
 
-    # shellcheck disable=SC1076
-    # shellcheck disable=SC1072
+    # shellcheck disable=SC1091
     source /etc/os-release || { echo "Missing /etc/os-release file." ; exit 1 ; }
 
     echo -e "Detected OS: \033[1m$NAME\033[0m\n"
@@ -76,12 +163,13 @@ function manual_install () {
             echo "Installed manpage: $out.gz"
         done
     else
-        echo -e "\033[31mPandoc is not installed. Skipping manpage installation.\033[0m"
+        echo -e "configure: pandoc is not installed. Skipping manpage generation."
     fi
 
     echo ""
 
     # enable the service
+    # shellcheck disable=SC2086
     case "$(systemctl is-enabled $_app_name.service)" in
         enabled|static                  )
             echo -e "\033[32mService $_app_name is already enabled.\033[0m"
@@ -99,57 +187,10 @@ function manual_install () {
             echo -e "\033[31mService $_app_name does not exist.\033[0m"
             exit 1
         ;;
-        *                       )
+        *                               )
             echo -e "\033[31mService $_app_name is not enabled.\033[0m"
         ;;
     esac
-
-}
-
-function Initialize_build () {
-
-    # Manually required system packages
-    _required=( debhelper dh-make git dpkg-changelog pandoc )
-
-    _missing=()
-
-    echo -e "Setting up the build environment..\n"
-
-    # Check if the HowToNebie APT repository is available
-    if ! grep -q "howtonebie" /etc/apt/sources.list /etc/apt/sources.list.d/* 2>/dev/null; then
-        echo -e "$_missingRepo"
-    else
-        echo -e "\033[32mHowToNebie APT repository is available.\033[0m\n"
-    fi
-    echo -e "🔍 Checking for build requirements\n"
-
-    for pkg in "${_required[@]}"; do
-        if check_installed "$pkg"; then
-            echo -e "$pkg $_pass"
-        else
-            echo -e "$pkg $_fail"
-            _missing+=( "$pkg" )
-        fi
-        sleep 0.33
-    done
-
-    # If _missing is not empty, print a message and exit
-    if [ ${#_missing[@]} -ne 0 ]; then
-        echo -e "\n\n\033[31mThe following packages are missing:\033[0m"
-        for pkg in "${_missing[@]}"; do echo -e "  - $pkg" ; done
-        echo -e "\nPlease install them using your package manager (e.g. \`sudo apt install <package>\`)"
-        exit 1
-    fi
-
-    for m in doc/man/*.md; do \
-		base=$(basename "$m" .md)
-		out="doc/man/${base}"
-		pandoc "$m" -s -t man -o "$out"
-	done
-
-    echo "" ; dpkg-changelog ; echo -e "\n\n\033[32mBuild environment initialized successfully!\033[0m\n"
-
-    echo -e "You can now build the package using \`$0 build\`"
 
 }
 
@@ -168,7 +209,7 @@ _systemd_dir="/usr/lib/systemd/system"
 
 # Files to be installed
 _app="$_app_name"
-_app_conf="grub_btrfsd"
+_app_conf="$_app_name.conf"
 _app_service="$_app_name.service"
 _app_completion="completion/$_app_name"
 _copyright="COPYING"
@@ -176,13 +217,14 @@ _readme="README.md"
 _coc="CODE_OF_CONDUCT.md"
 _version="docs/version"
 _app_man="man/$_app_name.1.md"
-_conf_man="man/$_app_name-conf.1.md"
+_conf_man="man/$_app_name.conf.5.md"
 
 _gpg_id=""
 _sign=true
 
 _pass="[\033[32m\u2714\033[0m]"
 _fail="[\033[31mx\033[0m]"
+_waring="[\033[33m!\033[0m]"
 
 _rootInstructions="$(cat <<-EOF
 To install this package, you need to run this script as root.
@@ -190,23 +232,13 @@ EOF
 )"
 
 _helpInfo="$(cat <<-EOF
-Configure script for the Polka-Dots Dark GRUB theme.
+Configure script for $_app_name - A Btrfs snapshot management tool.
 
 Usage: $0 [options] flags ARG..
 
 Options:
     build           Build the DEB package using dpkg-buildpackage. if no other
                     options are specified the build may fail.
-
-    --gpg-id        Specify the GPG key ID to sign the package. This option over-
-                    rides the --no-sign option.
-
-    --no-sign       Do not sign the package. This options is overridden by --gpg-id.
-
-    init            Initialize the build environment. The required packages will
-                    be checked and the build environment will be set up. Including
-                    the HowToNebie APT repository and the dpkg-changelog is
-                    installed
 
     install         Install the application, useful for non Debian/Ubuntu systems.
                     This option requires root privileges.
@@ -216,34 +248,39 @@ Options:
     help            Show this help message and exit.
 
 Build Flags:
-    --gpg-id        Specify the GPG key ID to sign the package. This option over-
-                    rides the --no-sign option.
-    --no-sign       Do not sign the package. This options is overridden by --gpg-id.
+    --build-type TYPE
+                    Specify the build type. Valid values are: binary, source, full.
+                    Default is binary.
+
+    --sign-key GPG_ID
+                    Specify the GPG key ID to sign the package. If not specified,
+                    the package will not be signed.
+
+    --no-sign       Do not sign the package. Overrides --sign-key.
+
+    --root-command COMMAND
+                    Specify the command to run as root. Valid values are: fakeroot,
+                    sudo, super, really. Default is fakeroot.
 
 Examples:
-    $0 build --gpg-id YOUR_GPG_ID
-    $0 build --no-sign
+    $0 build --build-type binary
+    $0 build --no-sign --root-command sudo
 EOF
 )"
 
 _missingRepo="$(cat <<-EOF
-\033[31mHowToNebie APT repository is not available.\033[0m
+HowToNebie APT repository is not available on your system.
 
 Please add the HowToNebie APT repository to your system.
 You can find instructions here: https://repository.howtonebie.com
 After adding the repository to your system, run:
 
-    \033[1m  sudo apt update\033[0m - Then run this script again."
+    sudo apt update\033[0m - Then run this script again."
 EOF
 )"
 
-# shellcheck disable=SC2221
-# shellcheck disable=SC2222
 case "$1" in
     build                     ) build_deb "$@"                     ;;
-    gpg-id                    ) _gpg_id="$2"              ; shift  ;;
-    no-sign                   ) _sign=false                        ;;
-    init                      ) Initialize_build                   ;;
     install                   ) manual_install                     ;;
     reset                     ) reset_env                          ;;
     help                      ) echo -e "$_helpInfo"               ;;
